# Travic-CI-Config file for \Org_Heigl\Color
#
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  allow_failures:
  - php: nightly

jobs:
  include:
  - stage: check
    php: 7.2
    script: composer cs-check
  - stage: test
  - stage: coverage
    php: 7.2
    before_install:
    - travis_retry composer self-update
    script: skip
    after_script:
    - travis_retry composer require --dev satooshi/php-coveralls
    - composer test-coverage
    - travis_retry composer upload-coverage

before_install:
- travis_retry composer self-update
- phpenv config-rm xdebug.ini

install:
- travis_retry composer install

script:
- composer test
